rewrite ^/aba$ /aba-therapy permanent;
rewrite ^/autismevaluations$ /autism-evaluations permanent;
rewrite ^/learnersocialclub$ /learner-social-club permanent;
rewrite ^/library/page/1$ /library permanent;
rewrite ^/es/library/page/1$ /es/library permanent;
rewrite ^/ar/library/page/1$ /ar/library permanent;
rewrite ^/library/author/rula-diab/page/1$ /library/author/rula-diab permanent;
rewrite ^/es/library/author/rula-diab/page/1$ /es/library/author/rula-diab permanent;
rewrite ^/ar/library/author/rula-diab/page/1$ /ar/library/author/rula-diab permanent;
